version: "3.9"

services:

  # api:
  #   build: .
  #   container_name: node_api
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #     - redis
  #   volumes:
  #     - .:/usr/src/app
  #   command: npm run dev  # or: node server.js

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
